image: 'inhumantsar/ansible:docker'

variables:
    DOCKER_DRIVER: overlay2

services:
    - 'docker:dind'    

test:
    variables:
        WORKDIR: "$CI_PROJECT_DIR"
    script:
        - /start.sh -vvv -c local
        - /start.sh -vvv -c local -e dockerautoproxy_config_path=/tmp
